const ch21Questions = [
  {
    "id": "ch21_1",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "1、2023 年5月第47题（此题为常规重点考题，建议举一反三）\n关于风险分析的技术，不正确的是 （ 47 ） 。",
    "options": [
      "概率影响矩阵适用于两个以上的参数对风险进行分类的情况",
 "蒙特卡洛分析，是使用模型模拟大量单个项目风险和其他不确定性来源的综合影响，以评估它们对项目目标的潜在影响",
 "敏感性分析，是将项目结果变化与定量风险分析模型中的要素变化之间建立联系的方法",
 "影响图是不确定条件下进行决策的图形辅助工具"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险相关工具，必须会。\nP451 页，如果使用了两个以上的参数对风险进行分类，那就不能使用概率和影响矩阵，而需要使用其他图形。例如，和气泡图能显示三维数据。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_2",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "2、我根据23 年11月第2 批考点原创的模拟题 （此题为常规重点考题，建议举一反三）\n采用较简单的流程、进行更多次测试和选用更可靠的卖方属于（     ） 策略。",
    "options": [
      "减轻",
 "规避",
 "上报",
 "转移"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险的应对措施，必须会。\n\nP460, 风险减轻是指采取措施来降低威胁发生的概率和影响。提前采取减轻措施通常比威胁出现后尝试进行弥补更加有效。减轻措施包括采用较简单的流程、进行更多次测试和选用更可靠的卖方。还可能涉及原型开发，以降低从实验台模型放大到实际工艺或产品中的风险。如果无法降低概率，也许可以从决定风险严重性的因素入手，来减轻风险发生的影响。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_3",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "3、我根据23 年11月第2 批考点原创的模拟题（此题为常规重点考题，建议举一反三）\n以下（     ） 不是定量风险分析的工具和技术。",
    "options": [
      "气泡图",
 "期望货币值",
 "蒙特卡洛",
 "敏感性分析"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查定量风险分析的工具，必须会。\n\nP454-45G, 气泡图是定性风险分析的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_4",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "4、我根据23 年11月第2 批考点原创的模拟题（此题为常规重点考题，建议举一反三）\n以下关于气泡图的说法中，错误的是（     ）。",
    "options": [
      "气泡图能显示三维数据",
 "在气泡图中，把每个风险都绘制成一个气泡，并用X 轴值、Y 轴值和气泡大小来表示风险的 （ 3 ） 个参数。",
 "气泡图中，可以用X 轴代表可监测性，Y 轴代表邻近性，影响值则以气泡大小表示。",
 "气泡图是识别风险的工具"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查气泡图，必须会。\n\nP451, 气泡图能显示三维数据。在气泡图中，把每个风险都绘制成一个气泡，并用 X 轴值、Y 轴值和气泡大小来表示风险的 3 个参数。和气泡图中 X 轴代表可监测性，Y 轴代表邻近性，影响值则以气泡大小表示。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_5",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "5、我根据23 年11月第2 批考点原创的模拟题\n敏感性分析的结果通常用（     ） 来表示。",
    "options": [
      "气泡图",
 "龙卷风图",
 "SWOT",
 "概率影响矩阵"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 本题考查敏感性风险，必须会。\n\nP455, 敏感性分析的结果通常用龙卷风图来表示。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_6",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "6、我根据23 年11月第3批考点原创的模拟题\n以下关于风险管理的过程排序，正确的是（     ）。\n①规划风险管理\n②识别风险\n③实施定性风险分析\n④实施定量风险分析\n⑤规划风险应对\n⑥实施风险应对\n⑦监督风险",
    "options": [
      "①②③④⑤⑥⑦",
 "①②⑤⑥⑦③④",
 "⑥⑦③④①②⑤",
 "③④①②⑤⑥⑦"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理过程，必须会。\nP436-437, 请把答案A 认真读就好。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_7",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "7、我根据23 年11月第 3批考点原创的模拟题 （此题为常规重点考题，建议举一反三）\n在定量风险分析中，使用模型来（     ） 单个项目风险和其他不确定性来源的综合影响，以评估它们对项目目标的潜在影响。（     ） 通常采用蒙特卡洛分析。",
    "options": [
      "模拟",
 "敏感性分析",
 "PERT",
 "EMV"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理过程，必须会。\nP454，模拟: 在定量风险分析中，使用模型来模拟单个项目风险和其他不确定性来源的综合影响，以评估它们对项目目标的潜在影响。模拟通常采用蒙特卡洛分析。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_8",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "8、我根据23 年11月第3批考点原创的模拟题\n风险报告第 1 次在（     ） 输出。",
    "options": [
      "识别风险",
 "规划风险管理",
 "定性风险分析",
 "定量风险分析"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险报告的相关内容，必须会。\n\nP447, 风险报告提供关于整体项目风险的信息, 以及关于已识别的单个项目风险的概述信息。风险报告的编制是一项渐进式的工作。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_9",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "9、我根据23 年11月第3批考点原创的模拟题\n（     ） 过程是对风险进行优先级排序。",
    "options": [
      "实施定性风险分析",
 "实施定量风险分析",
 "风险识别",
 "规划风险应对"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理的基本内容，必须会。\nP448，实施定性风险分析是通过评估单个项目风险发生的概率和影响及其他特征，对风险进行优先级排序，从而为后续分析或行动提供基础的过程。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_10",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "10、2023 年11月第4批 （此题为常规重点考题，建议举一反三）\n整体项目风险应对策略不包括（     ）。",
    "options": [
      "开拓",
 "接受",
 "上报",
 "转移或分享"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 本题考查风险的应对措施，必须会。\nP461-462, 整体项目风险应对策略: （ 1 ） 规避 （ 2 ） 开拓 （ 3 ） 转移或分享 （ 4 ） 减轻或提高 （ 5 ） 接受。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_11",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "11、2024 年5月第1批\n在项目执行过程中，项目经理发现项目进展顺利，但某些潜在风险因素仍然存在。为了确保项目能够顺利完成，项目经理应采取（     ） 措施，有效地监督这些风险。",
    "options": [
      "定期进行风险审查会议，并更新风险登记册",
 "减少项目开支，以降低潜在风险的影响",
 "分析风险因素对项目的潜在影响，并调整项目计划",
 "增加项目预算，以应对可能出现的风险"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险审查会等相关内容，必须会。\n\nP467 页，适用于监督风险过程的会议是风险审查会。应该定期安排风险审查，来检查和记录风险应对在处理整体项目风险和已识别单个项目风险方面的有效性。\n在风险审查中，还可以识别出新的单个项目风险 （包括已商定应对措施所引发的次生风险） 、重新评估当前风险、关闭已过时风险、讨论风险发生所引发的问题，以及总结可用于当前项目后续阶段或未来类似项目的经验教训。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_12",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "12、2024 年5月第1批（此题为常规重点考题，建议举一反三）\n在一个大型项目实施过程中，项目经理发现项目风险已经发生，并且对项目进度和成本产生了显著影响。为了准确评估风险对项目目标的影响程度，项目经理应该采取的定量风险分析技术是（     ） 。",
    "options": [
      "风险分类",
 "风险数据质量评估",
 "风险概率和影响评估",
 "敏感性分析"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险管理的工具等相关内容，必须会。\nP455 页，用于实施风险定性分析的工具与技术有:专家判断、访谈、风险数据质量评估、\n风险概率和影响评估、其他风险参数评估、引导、风险分类、概率和影响矩阵、层级图、会议。\n用于实施风险定量分析的工具与技术有:专家判断、访谈、引导、不确定性表现方式、模拟、敏感性分析、决策树分析、影响图。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_13",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "13、2024 年5月第1批\n关于规划风险管理过程的描述，不正确的是（     ）。",
    "options": [
      "规划风险管理在项目实施阶段开始，并在项目执行期间持续进行",
 "规划风险管理是定义如何实施项目风险管理活动的过程",
 "规划风险管理的主要作用是确保风险管理的水平、方法和可见度与项目风险程度相匹配",
 "干系人分析法可用于规划风险管理过程"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查规划风险管理的工具等相关内容，必须会。\nP439 页，规划风险管理过程在项目立项阶段就应开始，并在项目早期完成。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_14",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "14、2024 年5月第2批（此题为常规重点考题，建议举一反三）\n关于规划风险应对过程的概述，不正确的是（     ）。",
    "options": [
      "如果选定的策略并不完全有效，需要制定应急计划，识别采取风险应对措施后仍然存在的未被完全消除的次生风险",
 "风险应对方案可以用结构化的决策技术来选择最适当的应对策略，为每个风险选择最可能有效的策略或策略组合",
 "对于大型或复杂的项目，可能需要以数学优化模型或实际方案分析为基础，进行备选风险应对策略经济分析",
 "风险应对方案应在当前项目背景下现实可行，获得全体干系人同意，并由一名责任人具体负责"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查规划风险应对的相关内容，必须会。\n\nP458 页。风险应对方案应该与风险的重要性相匹配，并且能够经济有效地应对挑战，同时在当前项目背景下现实可行，获得全体干系人的同意，并由一名责任人具体负责。往往需要从几套可选方案中选出最优的风险应对方案，为每个风险选择最可能有效的策略或策略组合。可用结构化的决策技术来选择最适当的应对策略; 对于大型或复杂项目，可能需要以数学优化模型或实际方案分析为基础，进行备选风险应对策略经济分析。\n\n要为实施商定的风险应对策略制定具体的应对行动。如果选定的策略并不完全有效，或者发生了已接受的风险，就需要制订应急计划。同时，也需要识别次生风险。次生风险是实施风险应对措施直接导致的风险。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_15",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "15、2024 年5月第2 批\n适用于识别风险过程的数据分析技术是（     ）。",
    "options": [
      "核查单",
 "头脑风暴",
 "访谈",
 "SWOT 技术"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险识别的工具，必须会。\nP446 页。适用于识别风险过程的数据分析技术主要包括:\n （ 1 ） 根本原因分析 \n （ 2 ） 假设条件和制约因素分析 \n （ 3 ） SWOT 分析 \n （ 4 ） 文件分析。\n核查单、头脑风暴、访谈属于数据收集技术。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_16",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "16、2024年5月第2批\n关于项目风险管理过程的描述，不正确的是（     ）。",
    "options": [
      "实施风险应对是执行商定的风险应对计划的过程，需要在整个项目期间开展",
 "在项目实际进展中，项目风险管理过程中的各个过程会相互交琶，相互作用",
 "敏捷或适应型方法管理的项目，在每个迭代期间应该识别、分析和管理风险",
 "影响风险规划管理过程的组织过程资产是组织或关键干系人设定的整体风险的临界值"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险管理的相关内容，必须会。\n\nP439 页。影响规划风险管理过程的组织过程资产主要包括: 组织的风险政策; 风险类别，可能会用风险分解结构来表示; 风险概念和术语的通用定义; 风险描述的格式; 风险管理计划、风险登记册和风险报告的模板; 角色与职责; 决策所需的职权级别; 经验教训知识库，其中包念以往类似项目的信息等。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_17",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "17、2025 年5月第1批\n项目风险管理的首要目标是（     ）。",
    "options": [
      "减轻威胁或强化机会",
 "关注高概率风险",
 "将所有风险转移给第三方",
 "消除所有项目风险"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理的目标，必须会。\nP431, 项目风险管理的目的在于降低风险不利影响，提高项目成功的可能性。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_18",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "18、2025 年5月第1批\n在定量风险分析中,预期货币价值 （EMV） 的计算公式是（     ）。",
    "options": [
      "路径净值/风险概率",
 "∑(风险概率X收益)",
 "风险概率 X 路径净值",
 "∑(风险概率X路径净值)"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查 EMV 的计算公式，必须会。\nP45G，最基本的定义。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_19",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "19、2025 年5月第1批\n （ 5 ） 不是规划风险管理过程的输入。",
    "options": [
      "风险登记册",
 "干系人登记册",
 "项目管理计划",
 "组织的风险政策"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查规划风险管理的输入，必须会。\nP439，风险登记册是识别风险的输出。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_20",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "20、2025 年5月第1批\n某信息系统开发项目中，技术负责人被指定为“核心算法性能不足”风险的责任人，需优化算法。但该负责人忙于其他任务，迟迟未行动。项目经理适家采取的措施是（     ），以推动其实施风险应对。",
    "options": [
      "与技术负责人协商调整其绩效考核指标，将算法优化纳入KPI",
 "和暂停负责人其他任务，强制其优先处理风险",
 "要求团队其他成员接手算法优化工作",
 "直接将该风险升级汇报给发起人，从发起人处申请风险应对方案"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 本题考查应对风险的内容，必须会。\n\n选项A: 将算法优化纳入 KP1 可以激励技术负责人重视该任务，但其效果可能滞后，尤其是当风险需要紧急处理时。此外，调整绩效考核需经过组织流程，可能无法立即解决问题。\n\n选项B: 若风险紧近，项目经理有权重新分配资源，暂停负责人当前任务以优先处理风险。\n\n这是直接且高效的措施，符合项目管理中“确保责任人有足够资源”的原则，尤其适用于需要及早处理的情况。\n\n选项 C: 若技术负责人具备独特能力，其他成员可能无法胜任。更换责任人可能影响效率，且题目未提及团队能力守余，故该选项可行性较低。\n\n选项D: 升级通常用于超出项目经理权限的情况。当前问题属于团队内部资源调配，直接升级可能显得管理能力不足，且发起人介入并非最优解。\n\n根据题目意思，这是“核心算法性能不足”风险，建议马上处理，不要等黄花菜凉了!",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_21",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "21、2025 年5月第2批（此题为常规重点考题，建议举一反三）\n（     ） 可用于评估风险管理过程的有效性。",
    "options": [
      "储备分析",
 "技术绩效分析",
 "风险报告",
 "风险审计"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险管理的相关知识，必须掌握。\n\nP467，风险审计是一种审计类型，可用于评估风险管理过程的有效性。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_22",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "22、2025 年5月第2 批\n适用于识别风险过程的数据收集技术主要包括（     ）。\n①头脑风暴\n②访谈\n③核查单\n④专家判断\n⑤文件分析",
    "options": [
      "③④⑤",
 "①③④",
 "②④⑤",
 "①②③"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查识别风险的相关知识，必须掌握。\nP445, 适用于识别风险过程的数据收集技术主要包括: 头脑风暴、核查单、访谈。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_23",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "23、2025 年5月第2批（此题为常规重点考题，建议举一反三）\n用较简单的流程，进行更多次测试选用更可靠的卖方属于 （     ） 风险应对策略。延长进度计划或缩小范围属于（     ） 风险应对策略。",
    "options": [
      "减轻 减轻",
 "减轻 规避",
 "转移 减轻",
 "接受 规避"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 本题考查风险应对的相关知识，必须掌握。\n\nP460，规避措施可能包括消除威胁的原因、延长进度计划、改变项目策略，或缩小范围。有些风险可通过澄清需求、获取信息、改善沟通或取得专有技能来加以规避。\n\n减轻措施包括采用较简单的流程、进行更多次测试和选用更可靠的卖方。还可能涉及原型开发，以降低从实验台模型放大到实际工艺或产品中的风险。如果无法降低概率，也许可以从决定风险严重性的因素入手，来减轻风险发生的影响。例如，在一个系统中加入完余部件，可减轻原始部件故障所造成的影响。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_24",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "24、2025 年5月第2批\n关于项目风险管理过程的描述，不正确的是（     ）。",
    "options": [
      "规划风险应对过程会定义如何实施项目风险管理活动",
 "实施定性风险分析过程会对风险进行优先级排序",
 "识别风险过程会识别单个项目风险以及整体项目风险的来源",
 "实施风险应对过程会执行商定的风险应对计划"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理的相关知识，必须掌握。\n\nP457, 规划风险的应对措施是为了应对项目风险,而制定可选方案、选择应对策略并商定应对行动的过程。本过程的主要作用: \n①制定应对整体项目风险和单个项目风险的适当方法; \n②分配资源，并根据需要将相关活动添加进项目文件和项目管理计划中。\n别把规划风险管理和规划风险应对摘混了。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_25",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "25、1、以下关于实施风险应对的说法，错误的是（     ）。",
    "options": [
      "实施风险应对是执行商定的风险应对计划的过程。本过程的主要作用: ①确保按计划执行商定的风险应对措施，②管理整体项目风险入口、最小化单个项目威胁，以及最大化单个项目机会。",
 "实施风险应对可能导致项目团队派工单的更新",
 "风险登记册、风险报告是实施风险应对的输入",
 "SWOT 是实施风险应对的工具"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查 SWOT 等内容，必须会。\n\nP446, SWOT 是风险识别的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_26",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "26、2、马军老师正在进行整体项目风险应对策略的制定，针对“整体项目风险有严重的负面影响，并已超出商定的项目风险临界值”的情况，可以选择 （     ） 策略。",
    "options": [
      "规避",
 "开拓",
 "转移或分享",
 "减轻或提高"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险的应对措施，必须会。\n\nP461, 如果整体项目风险有严重的负面影响, 并已超出商定的项目风险临界值， 就可以采用规避策略。\n此策略涉及采取集中行动，弱化不确定性对项目整体的负面影响，并将项目拉回到临界值以内。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_27",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "27、3、以下风险参数中，（     ） 指标是风险在多长时间后会影响一项或多项项目目标。",
    "options": [
      "紧迫性",
 "邻近性",
 "连通性",
 "密切度"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 本题考查邻近性等名词定义，必须会。\nP450, 邻近性: 风险在多长时间后会影响一项或多项项目目标。时间短就说明邻近性高。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_28",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "28、4、以下关于风险管理的内容，错误的是（     ）。",
    "options": [
      "通常借助风险分解结构（RBS ） 来构建风险类别。风险分解结构是潜在风险来源的层级展现。",
 "应在风险管理计划中记录项目关键干系人的风险偏好。他们的风险偏好会影响规划风险管理过程的细节。",
 "核查单简单易用，而且可能穷尽所有风险。",
 "提示清单是关于可能引发项目风险来源的风险类别的预设清单。在采用风险识别技术时，提示清单可作为框架用于协助项目团队形成想法。"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 本题考查核查单等名词定义，必须会。\n\nP445, 核查单简单易用，但是不能穷尽所有风险",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_29",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "29、5、以下说法，不正确的是（     ）。",
    "options": [
      "并非所有项目都需要实施定量风险分析。项目风险管理计划会规定是否需要使用定量风险分析。",
 "敏感性分析: 有助于确定哪些单个项目风险或不确定性来源对项目结果具有最大的潜在影响。",
 "风险登记册提供关于整体项目风险的信息，以及关于已识别的单个项目风险的概述信息。",
 "风险概率和影响评估、风险分类、层级图、风险数据质量评估都是定性风险分析的工具。"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 本题考查风险报告等名词，必须会。\n\nP447, 风险报告提供关于整体项目风险的信息, 以及关于已识别的单个项目风险的概述信息。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_30",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "30、6、以下，（     ） 不是风险的特性。",
    "options": [
      "风险事件的随机性",
 "风险的相对性",
 "风险的可变性",
 "风险的必然性"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险特性。风险是一项不确定的事件，不具有必然性。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_31",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "31、7、为处理整体项目风险以及应对单个项目风险而制定可选方案、选择应对策略并商定应对行动，是（     ）过程的作用。",
    "options": [
      "规划风险应对",
 "实施风险应对",
 "实施定性风险分析",
 "实施定量风险分析"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理的各过程定义和作用，必须会。\nP437，规划风险应对:为处理整体项目风险以及应对单个项目风险而制定可选方案、选择应对策略并商定应对行动。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_32",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "32、8、以下（     ） 不属于风险管理计划的内容。",
    "options": [
      "风险管理策略",
 "干系人风险偏好",
 "风险概率和影响",
 "风险登记册"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险管理计划的内容，必须会。\n\nP440-P442, 风险登记册是在后期风险识别过程后才有的内容。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_33",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "33、9、在采用风险识别技术时,（     ） 可作为框架用于协助项目团队形成想法。可以用风险分解结构底层的风险类别作为（     ），来识别单个项目风险。",
    "options": [
      "提示清单",
 "文件分析",
 "核查单",
 "假设条件和制约因素分析"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查提示清单等名词的定义，必须会。\n\nP446, 提示清单是关于可能引发项目风险来源的风险类别的预设清单。可作为框架用于协助项目团队形成想法。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_34",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "34、10、以下（     ） 不属于完成风险识别后，风险登记册的内容。",
    "options": [
      "已识别风险的清单",
 "潜在风险责任人",
 "潜在风险应对措施清单",
 "整体项目风险的来源"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险登记册的内容，必须会。\nP447,D 是属于风险报告的内容。\n当完成识别风险过程时，风险登记册的内容主要包括:\n （ 1 ） 已识别风险的清单\n （ 2 ） 潜在风险责任人\n （ 3 ） 潜在风险应对措施清单",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_35",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "35、11、如果项目团队或项目发起人认为某威胁不在项目范围内，或提议的应对措施超出了项目经理的权限，就应该采用 （     ） 策略。",
    "options": [
      "上报",
 "规避",
 "转移",
 "减轻"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险的应对策略，必须会。\n\nP460, 如果项目团队或项目发起人认为某威胁不在项目范围内,或提议的应对措施超出了项目经理的权限，就应该采用上报策略。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_36",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "36、12、（     ） 策略将特定机会的出现概率提高到 100 确保其肯定出现，从而获得与其相关的收益。",
    "options": [
      "开拓",
 "提高",
 "分享",
 "接受"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险的应对策略，必须会。\n\nP460, 如果组织想确保把握住高优先级的机会,就可以选择开拓策略。此策略将特定机会的出现概率提高到 100 确保其肯定出现，从而获得与其相关的收益。开拓措施可能包括: 把组织中最有能力的资源分配给项目来缩短完工时间，或采用全新技术或技术升级来节约项目成本并缩短项目持续时间。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_37",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "37、13、（     ） 是把应对策略将导致的风险影响级别变更除以策略的实施成本所得到的比率，就代表了应对策略的成本有效性。比率越高，有效性就越高。",
    "options": [
      "备选方案分析",
 "成本收益分析",
 "多标准决策分析",
 "决策树分析"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 本题考查成本收益分析等名词，必须会。\n\nP462, 成本收益分析: 把应对策略将导致的风险影响级别变更除以策略的实施成本所得到的值。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_38",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "38、14、在进行监督风险时,（     ） 是把项目执行期间所取得的技术成果与取得相关技术成果的计划进行比较。",
    "options": [
      "技术绩效分析",
 "储备分析",
 "风险审计",
 "风险审查会"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查技术绩效分析等名词的定义，必须会。\nP467, 开展技术绩效分析, 把项目执行期间所取得的技术成果与取得相关技术成果的计划进行比较。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_39",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "39、15、公司任命小李作为项目经理，由于小李不能计划所有不测事件，它设立了一个应急储备，包括处理已知或未知风险的事件，资金或资源。这属于（     ）。",
    "options": [
      "风险回避，用应急储备避免风险的发生",
 "风险接受，用应急储备接受风险的发生",
 "风险转移，因为应急储备使项目成本提高",
 "风险回避，这是消极的应对方式"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 本题考查的是风险管理的相关知识。需要掌握。\n\nP460，风险接受是指承认威胁的存在。此策略可用于低优先级威胁，也可用于无法以任何其他方式经济有效地应对的威胁。接受策略又分为主动或被动方式。最常见的主动接受策略是建立应急储备，包括预留时间、资金或资源以应对出现的威胁; 被动接受策略则不会主动采取行动，而只是定期对威胁进行审查，确保其并未发生重大改变。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_40",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "40、16、风险相关的项目文件随着定量风险分析产生的信息而更新。（     ） 不是在定量风险分析过程中产生的。",
    "options": [
      "风险评级和分值",
 "量化风险优先级清单",
 "项目的概率分析",
 "实现成本和时间目标的概率"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查的是定量风险分析的基础知识。需要掌握。风险评级和分值属于定性风险分析，不属于定量风险分析。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_41",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "41、17、（     ） 属于定量风险分析的工具和技术。",
    "options": [
      "概率和影响矩阵",
 "风险数据质量评估",
 "风险概率和影响评估",
 "敏感性分析"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查定量风险分析的知识。需要掌握。\n\nP455，敏感性分析: 有助于确定哪些单个项目风险或不确定性来源对项目结果具有最大的潜在影响。它在项目结果变化与定量风险分析模型中的要素变化之间建立联系。敏感性分析的结果通常用龙卷风图来表示。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_42",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "42、18、某系统集成项目在进展到一半的时候识别到一个已知风险，项目经理启用应急储备来应对该风险，则（     ）。",
    "options": [
      "进度基准改变，成本基准不变",
 "进度基准不变，成本基准改变",
 "进度和成本基准都不改变",
 "进度和成本基准都应改变"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 本题考查是应急储备的基础知识。需要掌握。应急储备是包括在成本基准的一部分，也是包含在进度基准中的一段持续时间。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_43",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "43、19、（     ） 是评估风险数据对风险管理有用程度的一种技术，用来考察人们对风险的理解程度和风险数据的准确性、质量、可靠性、完整性。",
    "options": [
      "定量风险分析",
 "风险概率和影响评估",
 "风险紧迫性评估",
 "风险数据质量评估"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 本题考查风险数据评估等名词的相关内容。需要掌握。\n\nP449，风险数据质量评估。风险数据是开展定性风险分析的基础。风险数据质量评估旨在评价关于单个项目风险的数据的准确性和可靠性。使用低质量的风险数据，可能导致定性风险分析对项目来说基本没用。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_44",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "44、20、风险应对措施必须与（     ） 相匹配。",
    "options": [
      "风险类型",
 "风险收益",
 "风险的重要性",
 "风险预算"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 本题考查风险应对措施的相关内容。需要掌握。P458，风险应对方案应该与风险的重要性相匹配，并且能够经济有效地应对挑战，同时在当前项目背景下现实可行，获得全体干系人的同意，并由一名责任人具体负责。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_45",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "45、21、在某个采用敏捷开发模式的软件开发项目中，针对可能无法按时完成任务的风险，根据任务的难易程度对任务所需人力和时间做出如下分析，则该活动属于风险管理过程中的（     ）。\n<img src=\"images/ch21_45.png\" alt=\"任务分析表\" />",
    "options": [
      "定量风险评估",
 "定性风险评估",
 "识别风险",
 "规划风险应对"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查风险管理的相关内容。需要掌握。用具体的数字来量化，属于定量风险分析（评估）。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_46",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "46、22、以下（     ） 不是实施风险应对的输入。",
    "options": [
      "风险管理计划",
 "风险报告",
 "风险登记册",
 "变更请求"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是风险管理的输入输出工具和技术等。必须会。P464, 变更请求一般是输出。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_47",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "47、23、以下（     ） 不是识别风险的工具?",
    "options": [
      "假设条件和制约因素分析",
 "SWOT 分析",
 "文件分析",
 "干系人分析"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是风险管理的输入输出工具和技术等。P445-P446，干系人分析是规划风险管理的工具，而不是识别风险的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_48",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "48、24、以下（     ） 不是定性风险分析的工具?",
    "options": [
      "层级图",
 "气泡图",
 "概率影响和矩阵图",
 "影响图"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是风险管理的输入输出工具和技术等。必须会。P449-P451，影响图是定量风险分析的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_49",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "49、25、（     ） 不是监督风险的输入?",
    "options": [
      "绩效报告",
 "绩效数据",
 "绩效信息",
 "问题日志"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是风险管理的输入输出工具和技术等。必须会。P466-P467，绩效信息通常是输出。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_50",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "50、26、在风险识别过程中,（     ） 规定了哪些个人或小组可能参与项目的风险识别工作，还会详细说明哪些个人适合扮演风险责任人角色。",
    "options": [
      "干系人登记册",
 "干系人参与计划",
 "沟通管理计划",
 "资源管理计划"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 本题考查文件定义。P444，干系人登记册:规定了哪些个人或小组可能参与项目的风险识别工作，还会详细说明哪些个人适合扮演风险责任人角色。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_51",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "51、27、开展（     ） 来探索假设条件和制约因素的有效性，确定其中哪些会引发项目风险。从假设条件的不准确、不稳定、不一致或不完整，可以识别出威胁: 通过清除或放松会影响项目或过程执行的制约因素，可以创造出机会。",
    "options": [
      "假设条件和制约因素分析",
 "根本原因分析",
 "趋势分析",
 "蒙特卡洛"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是各名词的定义等。必须会。P446, 开展假设条件和制约因素分析来探索假设条件和制约因素的有效性, 确定其中哪些会引发项目风险。从假设条件的不准确、不稳定、不一致或不完整，可以识别出威胁; 通过清除或放松会影响项目或过程执行的制约因素，可以创造出机会。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_52",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "52、28、（     ）: 风险与其他单个项目风险存在关联的程度大小。如果风险与多个其他风险存在关联，（     ） 就高。",
    "options": [
      "连通性",
 "邻近性",
 "潜伏期",
 "战略影响力"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是各名词的定义等。必须会。P450，连通性: 风险与其他单个项目风险存在关联的程度大小。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_53",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "53、29、以下关于定量风险分析的说法中，错误的是（     ）。",
    "options": [
      "并非所有项目都需要实施定量风险分析。",
 "能否开展稳健的定量分析取决于是否有单个项目风险和其他不确定性来源的高质量数据，以及与范围、进度和成本相关的扎实的项目基线。",
 "定量分析适用于大型或复杂的项目，具有战略重要性的项目，合同要求进行定量分析的项目和主要干系人要求进行定量分析的项目。",
 "风险数据质量评估是定量风险分析的工具。"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是定量风险分析的相关内容。必须会。P449，风险数据质量评估是定性风险分析（而非定量）的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_54",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "54、30、在风险管理的裁剪考虑因素中,（     ） 是指由高水平创新、新技术采用、界面或外部依赖关系导致的项目复杂性提高,是否要求采用更稳健的风险管理方法?或者项目是否简单到只需用简化的风险管理过程?",
    "options": [
      "项目规模",
 "项目复杂性",
 "项目重要性",
 "开发方法"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查的是裁剪的相关内容。必须会。P438，裁剪时应考虑的因素主要包括: （ 2 ） 项目复杂性: 由高水平创新、新技术采用、界面或外部依赖关系导致的项目复杂性提高，是否要求采用更稳健的风险管理方法?",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_55",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "55、31、2017 年11月第45题\n风险可以从不同的角度，根据不同的标准来进行分类，百年不遇的暴雨属于 （ 45 ） 。",
    "options": [
      "不可预测风险",
 "可预测风险",
 "已知风险",
 "技术风险"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险分类的相关知识，需要掌握。这是一个定义题，既然是百年不遇，当然是不可预测的。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_56",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "56、32、2017 年11月第46题（此题为常规重点考题，建议举一反三）\n在风险识别时，可以用到多种工具和技术，其中， （ 46 ） 指的是从项目的优势、机会和威胁出发，对项目进行考察，从而更全面地考虑风险。",
    "options": [
      "头脑风暴法",
 "因果图",
 "SWOT 分析法",
 "专家判断法"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是 SWOT 的相关知识，需要掌握。这是一个定义题。S 是优势、W 是劣势，O 是机会、T 是威胁。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_57",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "57、33、2017 年11月第47题\n某项目有 40%的概率获利 10 万元，30%的概率会亏损 8 万元，30%的概率既不获利也不亏损，该项目的预期货币价值分析 （EMV） 是 （ 47 ） 。",
    "options": [
      "0元",
 "1.6 万元",
 "2 万元",
 "6.4 万元"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查的是 EMV 的相关知识，需要掌握。EMV=10*40%+（- （ 8 ） *30%+0*30%=4-2.4=1.6",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_58",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "58、34、2018 年5月第 45 题\n人们对风险事件都有一定的承受能力，当_ （ 45 ） 时，人们愿意承担的风险越大。",
    "options": [
      "项目活动投入的越多",
 "项目的收益越大",
 "个人、组织拥有的资源越少",
 "组织中高级别管理人员相对较少"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查的是风险管理的相关知识，掌握。常识题，人们得到利益越大，愿意承担的风险越大。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_59",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "59、35、2018 年11月第 46题\n关于项目风险管理的描述，不正确的是: （ 46 ） 。",
    "options": [
      "纯粹风险和人为风险在一定条件下可以相互转化",
 "项目风险既包括对项目目标的威胁，也包括促进项目目标的机会",
 "风险大多数随着项目的进展而不断变化，不确定性会逐渐减小",
 "风险后果包括后果发生的频率、收益或损失大小"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的基础常识。纯粹风险和投机风险在一定条件下可以相互转化。概念别搞混。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_60",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "60、36、2018 年11月第 48 题 （此题为常规重点考题，建议举一反三）\nA:公司刚刚中标一个大型系统集成项目，其中一台设备计划从国外采购，近期汇率波动明显，公司准备与客户协商使用国产设备进行蔡代，这是采用了 （ 48 ） 风险应对策略。",
    "options": [
      "回避",
 "转移",
 "减轻",
 "接受"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险管理的相关知识，需要掌握。回避风险指改变项目计划，以排除风险或条件，或者保护项目目标，使其不受影响。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_61",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "61、37、2019 年5月第 45 题\n关于项目风险的描述，不正确的是（     ）。",
    "options": [
      "已知风险与未知风险都可以进行管理",
 "风险既有可能对项目产生正面的影响，也有可能产生负面的影响",
 "同样的风险对于不同的主体有不同的影响",
 "收益越大，人们愿意承担的风险也就越大"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险管理的相关知识。不正确的是 A。未知风险通常无法主动管理，只能通过建立管理储备来应对其可能产生的影响。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_62",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "62、38、2019年5月第47题（此题为常规重点考题，建议举一反三）\n某信息系统建设项目中，为防范系统宕机风险，项目经理建议采购服务器时均配置冗余电源和冗余风扇。项目经理采用的风险应对策略为 （ 47 ） 。",
    "options": [
      "减轻",
 "转移",
 "规避",
 "消除"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险应对的相关知识，必须掌握。\n增加冗余电源和冗余风扇只能减少系统宕机的次数，不能消除隐患，也不是转移和规避。所以该题选A",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_63",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "63、39、2019年11月第45题\n关于风险的描述，正确的是 （ 45 ） 。",
    "options": [
      "不能带来机会、无获利可能的风险叫投机风险",
 "根据经验可以预见其发生，但不可预见其后果的风险叫做已知",
 "地震、百年不遇的暴雨等属于不可预测的风险",
 "风险是零和游戏，有人受损就有人获利"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是风险的相关知识。需要掌握。\n这个题目应该很简单。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_64",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "64、40、2019年11月第46题（此题为常规重点考题，建议举一反三）\n关于风险识别的描述，不正确的是 （ 46 ） 。",
    "options": [
      "应鼓励所有项目参与人员识别风险",
 "风险登记册的内容可能包括潜在应对措施清单",
 "定量风险分析不是必须的",
 "识别风险是一次性工作"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是风险识别的相关知识。需要掌握。\n送分的，风险识别需要全过程做。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_65",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "65、41、2019年11月第47题（此题为常规重点考题，建议举一反三）\n （ 47 ） 检查并记录风险应对措施在处理已识别风险及其根源方面的有效性，以及风险管理过程的有效性。",
    "options": [
      "风险再评估",
 "风险审计",
 "偏差和趋势分析",
 "技术绩效测量"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查的是风险审计的相关知识。需要掌握。\n基本的定义题，送分的。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_66",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "66、42、2020年11月第45题\n关于项目风险的描述，不正确的是 （ 45 ） 。",
    "options": [
      "风险具有随机性、相对性、可变性",
 "项目收益越大，人们愿意承担的风险越大",
 "项目投入越多，人们愿意承担的风险越大",
 "风险按照影响范围可分为局部风险和总体风险"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是风险管理的相关知识。需要掌握。\n送分的，基本常识。项目投入越多，人们愿意承担的风险越小。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_67",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "67、43、2020年11月第47题（此题为常规重点考题，建议举一反三）\n （ 47 ） 不属于定性风险分析的技术。",
    "options": [
      "风险数据质量评估",
 "概率和影响矩阵",
 "风险紧迫性评估",
 "预期货币价值分析"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是风险管理工具的相关知识。需要掌握。\nD是定量的。风险管理的工具是必考的考点。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_68",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "68、44、2020年11月第66题（此题为常规重点考题，建议举一反三）\n某公司主营产品有甲、乙、丙、丁四种。按照历史数据预测，下半年的市场需求总量可以有10万件、15万件和20万件三种情况，对应的概率分别为50%，30%，20%，不同情况下各产品带来的市场收益（单位:万元）如表所示，为了追求利润最大化，该公司应该生产 （ 66 ） 。\n<img src=\"images/ch21_68.png\" alt=\"产品收益表\" />",
    "options": [
      "甲",
 "乙",
 "丙",
 "丁"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是EMV的相关知识。需要掌握。\n送分的，概率影响相乘，比较大小。\n甲:-25*50%+35*30%+70*20%=-12.5+10.5+14=12\n乙:-20*50%+30*30%+65*20%=-10+9+13=12\n丙:-10*50%+25*30%+55*20%=-5+7.5+11=13.5\n丁:10*50%+15*30%+40*20%=5+4.5+8=17.5",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_69",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "69、45、2021年5月第45题\n关于风险的描述，不正确的是 （ 45 ） 。",
    "options": [
      "具有不确定性的事件不一定是风险",
 "项目风险既包括对项目目标的威胁，也包括促进项目目标的机会",
 "风险是零和游戏，有风险受益者，同时也有风险受害者",
 "在项目中应规避投机风险向纯粹风险的转化"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是风险的相关知识。需要掌握。\n风险不是零和游戏。在许多情况下，涉及风险的各有关方面都要蒙受损失，无一幸免。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_70",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "70、46、2021年5月第47题（此题为常规重点考题，建议举一反三）\n在项目定量风险分析技术中， （ 47 ） 需用一个模型，将详细规定的各项不确定性换算为它们对项目目标所产生的潜在影响。",
    "options": [
      "蒙特卡洛技术",
 "概率影响分析",
 "帕累托分析",
 "SWOT分析法"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是蒙特卡洛的相关知识。需要掌握。\n模型和模拟:一般采用蒙特卡洛技术。也叫做建模和仿真技术，不需要专家参与。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_71",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "71、47、2022年5月第46题\n关于风险的描述不正确的是 （ 46 ） 。",
    "options": [
      "具有不确定性的事件或活动也不一定是风险",
 "风险包括对目标的威胁，也包括促进目标的机会",
 "项目投入越大，可接受的风险越小",
 "因火灾造成停工引发的成本属于直接风险"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 考查的是风险的相关知识。需要掌握。\n风险损失的有形成本包括风险事件造成的直接损失和间接损失。\n （ 1 ） 直接损失。直接损失指财产损毁和人员伤亡的价值。如压缩空气机房在施工过程中失火。直接损失包括空压机的重置成本、受伤人员的医疗费、休养费、工资等。\n （ 2 ） 间接损失。间接损失指直接损失以外的它物损失、责任损失以及因此而造成的收益的减少。包括因灭火扑救、停工等发生的成本。所以D错误",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_72",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "72、48、2022年5月第48题\n关于风险的描述，正确的是 （ 48 ） 。",
    "options": [
      "风险审计可以在日常项目审查中进行，也可以单独召开风险审计会议",
 "蒙特卡洛分析有助于确定哪些风险对项目具有最大的潜在影响",
 "制定有效的风险应对策略需要风险量化分析",
 "建立应急储备，安排资金和资源应对风险是常见的问题风险策略"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险管理的相关知识。需要掌握。\n敏感性分析有助于确定哪些风险对项目具有最大的潜在影响。所以B错误;\n定量风险分析一般在定性风险分析之后进行，但是，经验丰富的风险经理有时在风险分析过程之后径直进行定量分析。有时，制定有效的风险应对策略并不需要风险量化分析。所以C错误;\n制定备用策略是在被选策略被证明无效或接受的风险发生时实施。通常，要为时间或成本分配应急储备金。最后，可制订应急计划并识别应急计划实施的触发条件。所以D错误;",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_73",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "73、49、2022 年11月第 46题\n关于风险的描述。不正确的（     ）。",
    "options": [
      "已知风险为其后果可以预见的风险",
 "随机性、相对性、可变性都是风险的属性",
 "按可预测性划分为可预测风险和不可预测风险两种",
 "项目管理人员必须避免投机风险转化为纯粹风险"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查风险管理的相关知识。需要掌握。\n按风险的可预测性划分，风险可以分为己知风险、可预测风险和不可预测风险。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_74",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "74、50、2022 年11月第 47题\n可用于风险识别的工具与技术是（     ）。",
    "options": [
      "决策树",
 "SWOT",
 "概率影响矩阵",
 "波士顿矩阵"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查风险识别的知识。需要掌握。\nSWOT是风险识别的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_75",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "75、51、2022 年11月第 48题\n应对消极威胁。不宜采用的策略是（     ）。",
    "options": [
      "提高",
 "回避",
 "转移",
 "接受"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 提高是积极风险策略。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_76",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "76、52、2019 年11月第 45 题\n（     ） 可以降低由于不确定性对项目整体产生负面影响。",
    "options": [
      "风险回避",
 "风险提高",
 "风险接受",
 "风险减轻"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险应对的相关知识。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_77",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "77、53、2019 年11月第 46 题\n关于风险的描述。不正确的是（     ）。",
    "options": [
      "风险具有相对性",
 "风险具有必然性",
 "风险具有可变性",
 "风险具有随机性"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查的是风险的相关性质。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_78",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "78、54、2020 年11月第 45 题\n以下（     ） 不是识别风险的输入。",
    "options": [
      "风险管理计划",
 "范围基准",
 "风险登记册",
 "资源管理计划"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是识别风险的相关知识。风险登记册是输出。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_79",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "79、55、2020 年11月第 46 题\n关于风险应对的描述。不正确的是（     ）。",
    "options": [
      "规避和减轻是针对威胁的",
 "开发和提高是针对机会的",
 "转移是通过第三方承担责任",
 "接受是所有的风险都不做处理"
    ],
    "correctAnswer": 3,
    "explanation": "【解析】: 主动接受可以建立应急储备。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_80",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "80、56、2021 年5月第 45 题\n关于风险的属性。不正确的是（     ）。",
    "options": [
      "随机性",
 "相对性",
 "必然性",
 "可变性"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 考查的是风险的属性。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_81",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "81、57、2021 年5月第 46 题\n（     ） 评估风险数据对风险管理有用的程度。",
    "options": [
      "概率影响矩阵",
 "风险数据质量评估",
 "技术绩效分析",
 "储备分析"
    ],
    "correctAnswer": 1,
    "explanation": "【解析】: 考查的是定性风险分析的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_82",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "82、58、2021 年11月第 45 题\n（     ） 属于识别风险的工具。",
    "options": [
      "核查单",
 "决策树",
 "敏感性分析",
 "储备分析"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是识别风险的工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_83",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "83、59、2021 年11月第 46 题\n项目经理将风险通过保险公司分担。属于（     ）。",
    "options": [
      "转移",
 "回避",
 "减轻",
 "接受"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险应对策略。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_84",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "84、60、2022 年5月第 45 题\n关于风险管理的描述。不正确的是（     ）。",
    "options": [
      "规划风险管理通常在项目立项阶段开始",
 "定性风险分析是对分析进行排序",
 "定量风险分析适用于所有项目",
 "监督风险在整个项目期间开展"
    ],
    "correctAnswer": 2,
    "explanation": "【解析】: 并不是所有项目都要定量。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_85",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "85、61、2022 年5月第 46 题\n适用于模拟综合影响的工具是（     ）。",
    "options": [
      "蒙特卡洛",
 "SWOT",
 "PESTEL",
 "龙卷风图"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是定量风险分析工具。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch21_86",
    "chapterId": "ch21",
    "type": "single",
    "difficulty": "medium",
    "content": "86、62、2022 年5月第 47 题\n项目经理发现风险有效策略失效，启动了备选策略。这是触发了（     ）。",
    "options": [
      "应急策略",
 "规避策略",
 "转移策略",
 "回避策略"
    ],
    "correctAnswer": 0,
    "explanation": "【解析】: 考查的是风险应对的相关知识。",
    "tags": ["ch21"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  }
];

// 将题目注入全局考试数据
if (typeof examData !== 'undefined') {
  examData.questions.push(...ch21Questions);
}

