const ch20Questions = [
  {
    "id": "ch20_1",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "1、2023 年5月第43题（此题为常规重点考题，建议举一反三）\n有效沟通活动具备的基本属性不包含 （ 43 ） 。",
    "options": [
      "沟通目的明确",
 "监督并衡量沟通的效果",
 "尽量了解沟通接收方，满足其需求和偏好",
 "频繁沟通，与沟通方进行全方位接触"
    ],
    "correctAnswer": 3,
    "explanation": "本题考查有效沟通活动的属性，必须会。\nP416 页。项目沟通过程通过沟通计划，为不同沟通人员和沟通内容选择合适的沟通方法，来预防理解和沟通错误。一般来说，有效的沟通活动和成果创建具有如下 3 个基本属性:\n1、沟通目的明确;\n2、尽量了解沟通接收方，满足其需求及偏好; \n3、监督并衡量沟通的效果。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_2",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "2、2023 年5月第44题\n关于规划沟通的描述，正确的是 （ 44 ） 。",
    "options": [
      "应根据需要在整个项目期间定期开展，持续保持其成果适用性",
 "确保所有沟通参与者之间的信息流动的最优化",
 "应尽量采用小组沟通方法来实现沟通管理计划所规定的沟通需求",
 "沟通管理计划基于项目范围管理计划制订和更新，与其同等重要"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查规划沟通的相关知识，必须会。\n\nP418 页 。规划沟通管理是基于每个干系人或干系人群体的信息需求、可用的组织资产，以及具体项目的需求，为项目沟通活动制定恰当的方法 and 计划的过程。本过程的主要作用: \n①及时向干系人提供相关信息; \n②引导干系人有效参与项目; \n③编制书面沟通计划。\n本过程应根据需要在整个项目期间定期开展。项目经理需在项目生命周期的早期，针对项目干系人多样性的信息需求，制订有效的沟通管理计划。应该在整个项目期间，定期审查本过程的成果并做必要修改，以确保其持续适用。\n例如：在干系人发生变化或每个新项目阶段开始时。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_3",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "3、2023 年5月第45题（此题为常规重点考题，建议举一反三）\n关于项目报告的描述，不正确的是 （ 45 ） 。",
    "options": [
      "项目报告发布是收集和发布项目信息的行为",
 "项目报告应尽量详尽，让所有干系人全面了解项目情况",
 "项目信息应发布给众多干系人",
 "可以定期或临时准备项目信息并编制项目报告"
    ],
    "correctAnswer": 1,
    "explanation": "本题考查项目报告的相关内容，必须会。\nP426 页。项目报告发布是收集和发布项目信息的行为。项目信息应发布给众多干系人群体。\n应针对每种干系人来调整项目信息发布的适当层次、形式和细节。从简单的沟通到详尽的定制报告和演示，报告的形式各不相同。可以定期准备信息或基于例外情况准备。虽然工作绩效报告是监控项目工作过程的输出，但是本过程会编制临时报告、项目演示、博客，以及其他类型的信息。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_4",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "4、我根据23 年11月第1批考点原创的模拟题 （此题为常规重点考题，建议举一反三）\n视频会议属于（     ）。",
    "options": [
      "互动沟通",
 "拉式沟通",
 "推式沟通",
 "非正式沟通"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查沟通方式，必须会。\n\nP421，沟通方法:\n\n （ 1 ） 互动沟通。在两方或多方之间进行的实时多向信息交换。它使用诸如会议、电话、即时信息、社交媒体和视频会议等沟通方式。\n\n （ 2 ） 推式沟通。向需要接收信息的特定接收方发送或发布信息。这种方法可以确保信息的发送，但不能确保信息送达目标受众或被目标受众理解。在推式沟通中，可以用于沟通的有:信件、备忘录、报告、电子邮件、传真、语音邮件、博客和新闻稿。\n\n （ 3 ） 拉式沟通。适用于大量复杂信息或大量信息受众的情况。它要求接收方在遵守有关安全规定的前提之下自行访问相关内容。这种方法包括门户网站、组织内网、电子在线课程、经验教训数据库或知识库。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_5",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "5、我根据23 年11月第1批考点原创的模拟题\n（     ） 负责确保完整地接收信息，正确地理解信息，并需要告知已收到或作出适当的回应。",
    "options": [
      "接收方",
 "发送方",
 "噪声",
 "媒介"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查沟通模型，必须会。\n\nP420-P421, 作为沟通过程的一部分, 发送方负责信息的传递, 确保信息的清晰性和完整性，并确认信息已被正确理解; 接收方负责确保完整地接收信息，正确地理解信息，并需要告知已收到或作出适当的回应。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_6",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "6、我根据23 年11月第2 批考点原创的模拟题\n以下（     ） 不是规划沟通管理的输入?",
    "options": [
      "项目章程",
 "资源管理计划",
 "需求文件",
 "干系人参与度评估矩阵"
    ],
    "correctAnswer": 3,
    "explanation": "本题考查规划沟通管理的输入，必须会。\n\nP419, 干系人参与度评估和矩阵是规划沟通管理的工具和技术。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_7",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "7、我根据23 年11月第2 批考点原创的模拟题（此题为常规重点考题，建议举一反三）\n马军老师在给大家讲课过程中,告诉大家 10 大管理的论文非常重要, 要大家不要去想押题，必须全面学习，大家也及时收到了消息，很多学员认可了马军老师的观点，但是他不去执行，目前是处于（     ）。",
    "options": [
      "已转化为积极的行动",
 "已收到",
 "已理解",
 "已认可"
    ],
    "correctAnswer": 3,
    "explanation": "本题考查沟通模型的状态，必须会。\n\nP415，沟通模型包含5 种状态: 已发送、已收到、已理解、已认可、已转化为积极的行动。\n （ 4 ） 已认可: 理解了传达的信息并不代表对方已同意这个观点。或许对方明白了发送者的意思，但完全不同意。因此，达成一致仍然是做出项目决策和有效沟通的关键一环。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_8",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "8、我根据23 年11月第 3批考点原创的模拟题\n（     ） 是确保满足项目及其干系人的信息需求的过程。本过程的主要作用是，按沟通管理计划干系人参与计划的要求优化信息传递流程。",
    "options": [
      "规划沟通",
 "管理沟通",
 "监督沟通",
 "规划干系人管理"
    ],
    "correctAnswer": 2,
    "explanation": "本题考查沟通管理各过程的定义，必须会。\n\nP427，监督沟通是确保满足项目及其干系人的信息需求的过程。本过程的主要作用是，按沟通管理计划干系人参与计划的要求优化信息传递流程。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_9",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "9、我根据23 年11月第3批考点原创的模拟题\n推式沟通主要是向特定接收方发送或发布信息，但不能确保信息被理解。在以下选项中，哪个最符合推式沟通的特点（     ）。",
    "options": [
      "通过视频会议进行的实时讨论",
 "通过电子邮件发送的工作报告",
 "通过社交媒体平台发布的信息",
 "通过电话进行的即时信息交流"
    ],
    "correctAnswer": 1,
    "explanation": "本题考查沟通方法，必须会。\nP421，沟通方法:\n （ 2 ） 推式沟通。向需要接收信息的特定接收方发送或发布信息。这种方法可以确保信息的发送，但不能确保信息送达目标受众或被目标受众理解。在推式沟通中，可以用于沟通的有:信件、备忘录、报告、电子邮件、传真、语音邮件、博客和新闻稿。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_10",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "10、2023 年11月第4批（此题为常规重点考题，建议举一反三）\n（     ） 不属于书面沟通的5C原则。",
    "options": [
      "简洁的表述（concise）",
 "可以证明的结论（certification）",
 "连贯的思维逻辑（coherent）",
 "清晰的目的和表述（clarity）"
    ],
    "correctAnswer": 1,
    "explanation": "本题考查 5C 原则，必须会。\nP416，在编制书面或口头信息的时候，应使用书面沟通的 5C 原则，以减轻理解错误:\n （ 1 ） 正确的语法和拼写\n （ 2 ） 简洁的表述\n （ 3 ） 清晰的目的和表述\n （ 4 ） 连贯的思维逻辑\n （ 5 ） 善用控制语句和承接",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_11",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "11、2023 年11月第4批\n项目经理需在项目生命周期的（     ）,针对项目干系人多样性的信息需求，制订有效的沟通管理计划。应该在（     ）期间，定期审查本过程的成果并做必要修改，以确保其持续适用。",
    "options": [
      "前期、项目后期",
 "早期、整个项目",
 "中期、项目后期",
 "整个周期、项目中期"
    ],
    "correctAnswer": 1,
    "explanation": "本题考查沟通管理计划的制定、更新，必须会。\n\nP418，项目经理需在项目生命周期的早期，针对项目干系人多样性的信息需求，制订有效的沟通管理计划。应该在整个项目期间，定期审查本过程的成果并做必要修改，以确保其持续适用。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_12",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "12、2023 年11月第4批（此题为常规重点考题，建议举一反三）\n在管理沟通过程中，某项目经理认为所谓的激烈的权力游戏、控制战术和冲突管理与自己的工作毫无关联，则他缺少人际关系交往中的（     ）。",
    "options": [
      "文化意识",
 "积极倾听",
 "政策意识",
 "人际交往"
    ],
    "correctAnswer": 2,
    "explanation": "本题考查政策意识等名词，必须会。\n\nP422, 政策意识有助于项目经理根据项目环境和组织的政策环境来规划沟通。政策意识是指对正式和非正式权力关系的认知，以及在这些关系中工作的意愿。理解组织战略、了解谁能行使权力和施加影响，以及培养与这些干系人沟通的能力，都属于政策意识范畴。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_13",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "13、2024年5月第1批\n项目沟通管理是确保及时、正确地产生、收集、分发、（     ）和处理项目信息所需的过程。",
    "options": [
      "存储",
 "分析",
 "接收",
 "分享"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查沟通管理的相关内容，必须会。\nP423 页。管理沟通是确保项目信息及时且恰当地收集、生成、发布、存储、检索、管理、监督和最终处置的过程。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_14",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "14、2024 年5月第1批\n“监督沟通”过程采用的措施不包括 （     ）。",
    "options": [
      "整理经验教训、开展团队观察",
 "审查问题日志、评估变更",
 "开展客户满意度调查",
 "识别和确定沟通需求"
    ],
    "correctAnswer": 3,
    "explanation": "本题考查监督沟通的相关内容，必须会。\nP427 页。监督沟通可能需要采取各种方法，例如，开展客户满意度调查、整理经验教训、开展团队观察、审查问题日志和评估变更。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_15",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "15、2024 年5月第1批\n在一个大型信息系统项目中，项目经理发现尽管已经建立了沟通机制，但团队间的沟通依然不顺畅，项目风险不断上升。项目经理应优先采取的措施是（     ）。",
    "options": [
      "监督沟通活动执行情况，审查并优化现有沟通机制",
 "引入新的沟通工具，提高信息传递效率",
 "增加每周的团队会议次数，强制团队成员交流",
 "对团队成员进行沟通技巧培训，提升沟通质量"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查监督沟通的相关内容，必须会。\nP427 页。监督沟通是确保满足项目及其干系人的信息需求的过程。本过程的主要作用是，按沟通管理计划干系人参与计划的要求优化信息传递流程本过程需要在整个项目期间开展。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_16",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "16、2024 年5月第2批（此题为常规重点考题，建议举一反三）\n关于管理沟通过程中工作绩效报告的描述，不正确的是（     ）。",
    "options": [
      "工作绩效报告通过分析绩效测量结果得出，能够提供关于项目工作绩效的信息",
 "工作绩效报告的典型示例包括状态报告、进展报告，是管理沟通过程的输出",
 "工作绩效报告可以包含挣值图表、缺陷直方图、合同绩效以及风险概述信息",
 "工作绩效报告可以表现为有助于制定决策和采取行动的仪表指示图"
    ],
    "correctAnswer": 1,
    "explanation": "本题考查工作绩效报告的相关内容，必须会。\n\nP424 页。工作绩效报告的典型示例包括状态报告、进展报告，是管理沟通过程的输入。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_17",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "17、2024 年5月第2批\n不能用于规划沟通管理过程的人际关系与团队技能是（     ）。",
    "options": [
      "冲突管理",
 "政策意识",
 "文化意识",
 "沟通风格评估"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查规划沟通的相关技术，必须会。\n\nP422 页。适用于规划沟通管理过程的人际关系与团队技能主要包括:\n （ 1 ） 沟通风格评估。\n （ 2 ） 政策意识\n （ 3 ） 文化意识。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_18",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "18、2024 年5月第2批\n适用于管理沟通过程的沟通技能不包括（     ）。",
    "options": [
      "数据挖掘",
 "沟通胜任力",
 "反馈",
 "演示"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查管理沟通的工具，必须会。\n\nP425 页。用于管理沟通过程的沟通技能主要包括:\n （ 1 ） 沟通胜任力 \n （ 2 ） 反馈 \n （ 3 ） 非口头技能 \n （ 4 ） 演示",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_19",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "19、2025 年5月第1批（此题为常规重点考题，建议举一反三）\n有效的沟通活动需具备的属性包括（     ），预防理解和沟通的错误。\n①沟通目的明确\n②简洁的表述，慎用控制语句\n③尽量了解沟通接收方，满足其需求及偏好;\n④监督并衡量沟通的效果",
    "options": [
      "①③④",
 "②③④",
 "①②③",
 "①②④"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查沟通的属性，必须会。\n\nP416，有效的沟通活动和成果创建具有如下 3 个基本属性: \n①沟通目的明确; \n②尽量了解沟通接收方，满足其需求及偏好;\n③监督并衡量沟通的效果。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_20",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "20、2025 年5月第1批\n （ 5 ） 是管理沟通过程的输出，其将被纳入（     ）中进行管理。",
    "options": [
      "项目沟通记录；项目文件",
 "风险报告；项目文件",
 "工作绩效报告；项目管理计划",
 "资源管理计划；项目管理计划"
    ],
    "correctAnswer": 0,
    "explanation": "本题考查管理沟通的输入输出，必须会。\nP426，项目沟通记录是管理沟通的输出。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_21",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "21、2025 年5月第2 批\n监督沟通过程的输入不包含（     ）。",
    "options": [
      "项目沟通记录",
 "工作绩效数据",
 "经验教训登记册",
 "计划沟通的实际开展情况"
    ],
    "correctAnswer": 3,
    "explanation": "本题考查监督沟通的输入，必须掌握。\nP428，输入包括项目管理计划、项目文件（如经验教训登记册、项目沟通记录）、工作绩效数据等。'计划沟通的实际开展情况'不是标准的输入术语描述。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_22",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "22、2025 年5月第2批 （此题为常规重点考题，建议举一反三）\n以下沟通方法中，属于推式沟通的是（     ）。\n①新闻稿\n②报告\n③门户网站\n④电子邮件\n⑤电子在线课程\n⑥公众号",
    "options": [
      "①③④⑤",
 "②③⑤⑥",
 "①②④⑥",
 "①②③④"
    ],
    "correctAnswer": 2,
    "explanation": "本题考查沟通方法的相关知识，必须掌握。\n\nP421, 推式沟通包括: 信件、备忘录、报告、电子邮件、传真、语音邮件、博客和新闻稿。公众号也属于推式，而门户网站、在线课程属于拉式。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_23",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "23、2025 年5月第2批\n关于沟通管理的描述，不正确的是（     ）。",
    "options": [
      "沟通是指用各种可能的方式来发送或接收信息",
 "管理沟通过程是确保满足项目及其干系人的信息需求",
 "项目经理的绝大多数时间都用于与团队成员和其他人员沟通",
 "项目沟通管理由制定策略和执行必要活动两部分组成"
    ],
    "correctAnswer": 1,
    "explanation": "本题考查沟通管理的相关知识，必须掌握。\nP423，管理沟通是确保项目信息及时且恰当地收集、生成、发布、存储、检索、管理、监督和最终处置的过程。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_24",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "1、以下说法，错误的是（     ）。",
    "options": [
      "项目沟通记录主要包括: 绩效报告、可交付成果的状态、进度进展等",
 "沟通记录是管理沟通的输出",
 "项目报告发布是收集和发布项目信息的行为，是管理沟通的工具",
 "写作风格可以达成共识、克服障碍（如小组缺乏活力）"
    ],
    "correctAnswer": 3,
    "explanation": "本题考查写作风格等。P424, 写作风格是指选择适当的语态、句子结构等。而达成共识、克服障碍是“引导”的作用。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_25",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "2、以下说法，错误的是（     ）。",
    "options": [
      "层级沟通是指干系人根据内部职权的不同采取不同方向的沟通方式",
 "影响沟通技术的选择的因素包括信息需求的紧迫性等",
 "干系人参与计划是管理沟通过程的输出",
 "质量报告是管理沟通过程的输入"
    ],
    "correctAnswer": 2,
    "explanation": "P424-P425, 干系人参与计划是管理沟通过程的输入，而不是输出。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_26",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "3、“我以我心照明月，奈何明月照沟渠 ”，可以理解为沟通模型里的（     ）出了问题。",
    "options": ["编码", "解码", "噪音", "媒介"],
    "correctAnswer": 1,
    "explanation": "本题考查沟通模型。对方误解了发送者的意思，属于解码环节出现问题。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_27",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "4、马军老师是某项目的项目经理...现在，项目的沟通渠道，增加了 （     ）条?",
    "options": ["48", "3", "6", "84"],
    "correctAnswer": 0,
    "explanation": "计算沟通渠道增加量。原人数为 （ 15 ） PM+配置经理+配置项+配置管理员+架构+10成员）。增加 3 人（风险+变更+测试），总人数 18。计算 （ 18 ） *17/ （ 2 ） - （ 15 ） *14/ （ 2 ） = 153 - 105 = 48。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_28",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "5、以下说法，错误的是 （     ）。",
    "options": [
      "项目经理每天给所有项目干系人通过邮件的方式汇报项目工作",
 "通过演示，取得了更好的沟通效果",
 "在进行沟通的时候，会进行沟通渠道的选择",
 "干系人的沟通需求属于沟通管理计划的内容"
    ],
    "correctAnswer": 0,
    "explanation": "每天给‘所有’干系人汇报工作是不现实且没必要的，干系人应按需进行沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_29",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "6、以下（     ）不属于沟通的 5C原则里的内容。",
    "options": [
      "正确的语法和拼写",
 "简洁的表述",
 "清晰的目的和表述",
 "积极倾听"
    ],
    "correctAnswer": 3,
    "explanation": "5C原则包括：正确的语法、简洁、清晰、连贯、控制。积极倾听是沟通技能，不属于5C。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_30",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "7、（     ）过程包含如下作用:\n①及时向干系人提供相关信息;\n②引导干系人有效参与项目\n③编制书面沟通计划。",
    "options": ["规划沟通管理", "管理沟通", "监督沟通", "干系人管理"],
    "correctAnswer": 0,
    "explanation": "P418, 规划沟通管理的作用。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_31",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "8、（     ）用于评估沟通风格并识别偏好的沟通方法、形式和内容的一种技术。",
    "options": ["沟通风格评估", "政策意识", "文化意识", "干系人参与度评估矩阵"],
    "correctAnswer": 0,
    "explanation": "P422, 沟通风格评估的定义。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_32",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "9、以下（     ）不属于沟通管理计划的内容。",
    "options": [
      "干系人的沟通需求",
 "接收信息的人员或群体",
 "用于传递信息的方法或技术",
 "项目沟通记录"
    ],
    "correctAnswer": 3,
    "explanation": "项目沟通记录是管理沟通的输出，不是规划阶段的计划内容。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_33",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "10、（     ）用于选择适当的语态、句子结构，以及使用适当的词汇 。",
    "options": ["写作风格", "媒介选择", "发送方-接收方模型", "演示"],
    "correctAnswer": 0,
    "explanation": "P424, 写作风格的定义。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_34",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "11、（     ）是经过裁剪的沟通技能的组合，有助于明确关键信息的目的、建立有效关系、实现信息共享和采取领导行为。",
    "options": ["沟通胜任力", "反馈", "非口头技能", "演示"],
    "correctAnswer": 0,
    "explanation": "P425, 沟通胜任力的定义。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_35",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "12、关于管理沟通的工具，不正确的是（     ）。",
    "options": [
      "沟通模型的各要素会影响沟通的效率和效果",
 "管理沟通过程中要确保已创建并发布的信息能够被接受和理解",
 "项目经理应定期或不定期进行绩效评估",
 "项目进行过程中需选择固定的沟通渠道"
    ],
    "correctAnswer": 3,
    "explanation": "沟通渠道会随实际情况变化，不能固定死。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_36",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "13、以下（     ）不是规划沟通管理的输入。",
    "options": ["干系人参与计划", "干系人登记册", "沟通管理计划", "资源管理计划"],
    "correctAnswer": 2,
    "explanation": "沟通管理计划是本过程的输出，不是输入。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_37",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "14、以下（     ）不是管理沟通的输入。",
    "options": ["变更日志", "问题日志", "质量报告", "项目沟通记录"],
    "correctAnswer": 3,
    "explanation": "项目沟通记录是管理沟通的输出。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_38",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "15、（     ）不是管理沟通的工具?",
    "options": ["干系人参与度评估矩阵", "沟通方法", "项目报告", "政策意识"],
    "correctAnswer": 0,
    "explanation": "干系人参与度评估矩阵是规划和监督过程的工具。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_39",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "16、在规划沟通管理过程中，（     ）显示了个体干系人当前和期望参与度之间的差距。",
    "options": ["干系人参与度评估矩阵", "沟通风格评估", "政策意识", "文化意识"],
    "correctAnswer": 0,
    "explanation": "P422, 干系人参与度评估矩阵的作用。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_40",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "17、在管理沟通过程中,（     ）运用反馈循环，为互动和参与提供机会，并清除障碍。",
    "options": ["发送方-接收方模型", "媒介选择", "写作风格", "引导"],
    "correctAnswer": 0,
    "explanation": "P424, 发送方-接收方模型的作用。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_41",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "18、（     ）主要包括绩效报告、进度进展、成本、演示等信息。",
    "options": ["项目沟通记录", "项目报告", "沟通管理计划", "质量报告"],
    "correctAnswer": 0,
    "explanation": "P426, 项目沟通记录的定义。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_42",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "19、（     ）是干系人根据职权不同采取向上、向下和横向等沟通方式。",
    "options": ["层级沟通", "官方沟通", "非官方沟通", "书面与口头沟通"],
    "correctAnswer": 0,
    "explanation": "P415, 层级沟通的定义。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_43",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "20、以下（     ）不属于沟通模型中的状态?",
    "options": ["已发送", "已撤回", "已收到", "已认可"],
    "correctAnswer": 1,
    "explanation": "沟通模型5种状态：已发送、已收到、已理解、已认可、已转化为积极行动。没有'已撤回'。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_44",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "21、在进行沟通管理中，（     ） 不是裁剪考虑的因素?",
    "options": ["干系人", "物理地点", "语言", "资源管理"],
    "correctAnswer": 3,
    "explanation": "P418, 裁剪因素不包括资源管理。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_45",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "22、沟通模型中，（     ）是把信息还原成有意义的思想或想法。",
    "options": ["编码", "解码", "媒介", "噪声"],
    "correctAnswer": 1,
    "explanation": "解码的定义。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_46",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "23、2017 年11月第 41题\n日常与人交往发生的误解，通常在 （ 41 ） 环节发生。",
    "options": ["编码", "解码", "媒介", "信息"],
    "correctAnswer": 1,
    "explanation": "对方误解你的意思了，通常是在解码环节出问题。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_47",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "24、2017 年11月第 42 题\n参加会议的人数为 12 人，沟通渠道有 （ 42 ） 条。",
    "options": ["66", "72", "96", "132"],
    "correctAnswer": 0,
    "explanation": "12*11/2 = 66。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_48",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "25、2018 年5月第 42 题\n电子邮件沟通属于（     ）。",
    "options": ["实时沟通", "推式沟通", "拉式沟通", "情境式沟通"],
    "correctAnswer": 1,
    "explanation": "电子邮件是典型的推式沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_49",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "26、2018 年11月第 43 题\n微信群属沟通模型中的 （ 43 ） 关键要素。",
    "options": ["编码", "解码", "噪声", "媒介"],
    "correctAnswer": 3,
    "explanation": "微信群是用来传递信息的工具，属于媒介。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_50",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "27、2019 年5月第 42题\n对于信息量很大或受众很多的情况，建议采用（     ） 沟通方式。",
    "options": ["拉式", "推式", "互动", "面对面"],
    "correctAnswer": 0,
    "explanation": "拉式沟通适用于大量复杂信息或大量信息受众。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_51",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "28、2019 年11月第 42题\n备忘录、报告、日志、新闻稿等沟通方式属于（     ）。",
    "options": ["推式沟通", "互动沟通", "拉式沟通", "非正式沟通"],
    "correctAnswer": 0,
    "explanation": "这些都是单向发送给特定人的，属于推式沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_52",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "29、2020 年11月第41题\n项目经理加上开发经理以及 10 名成员共 12 人，该团队内的沟通渠道共 （     ） 条。",
    "options": ["45", "55", "66", "78"],
    "correctAnswer": 2,
    "explanation": "12*11/2 = 66。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_53",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "30、2020 年11月第 42 题\n（     ） 不属于沟通管理过程的工具与技术。",
    "options": ["标杆对照", "信息管理系统", "沟通方法", "项目报告"],
    "correctAnswer": 0,
    "explanation": "标杆对照通常是质量规划或收集需求的工具。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_54",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "31、2021 年5月第41题\n（     ） 属于拉式沟通方法。",
    "options": ["电子邮件", "经验教训数据库", "视频会议", "备忘录"],
    "correctAnswer": 1,
    "explanation": "数据库属于拉式沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_55",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "32、2021 年5月第 42 题\n关于沟通管理过程的描述，正确的是（     ）。",
    "options": [
      "控制沟通是为了促进项目干系人之间实现有效沟通",
 "项目管理中出现的任何问题都可以通过沟通来解决",
 "管理沟通是识别和记录与干系人有效沟通的方式",
 "项目经理大多数的时间都用于沟通工作"
    ],
    "correctAnswer": 3,
    "explanation": "项目经理大约 90% 的时间在沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_56",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "33、2021 年11月第41题\n主动去访问项目相关的知识库，这种沟通属于（     ）。",
    "options": ["互动沟通", "拉式沟通", "推式沟通", "集中式沟通"],
    "correctAnswer": 1,
    "explanation": "主动访问库属于拉式沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_57",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "34、2021 年11月第 42 题\n（     ） 的目的是随时确保所有沟通参与者之间的信息流动的最优化。",
    "options": ["规划沟通管理", "管理沟通", "控制沟通", "改进沟通"],
    "correctAnswer": 2,
    "explanation": "控制（监督）沟通的目的。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_58",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "35、2022 年5月第 42 题\n某项目沟通渠道为 66，则该项目干系人为（     ） 人。",
    "options": ["9", "10", "11", "12"],
    "correctAnswer": 3,
    "explanation": "n*(n- （ 1 ） /2=66 => n=12。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_59",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "36、2022 年5月第 43题\n在项目沟通管理过程中，（     ） 是“管理沟通”过程的作用。",
    "options": [
      "确保所有参与者之间的信息流动的最优化",
 "促进项目干系人之间实现有效率且有效果的沟通",
 "识别与记录最有效的沟通方式",
 "针对关键指标的沟通可引发修正措施"
    ],
    "correctAnswer": 1,
    "explanation": "管理沟通的作用是促进有效沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  },
  {
    "id": "ch20_60",
    "chapterId": "ch20",
    "type": "single",
    "difficulty": "medium",
    "content": "37、2022 年11月第43题\n项目组原定的项目例会改为周二召开，这属于（     ）过程。",
    "options": ["实施整体变更控制", "规划沟通管理", "管理沟通", "控制沟通"],
    "correctAnswer": 3,
    "explanation": "例会调整属于对沟通活动的监督和调整，属于控制（监督）沟通。",
    "tags": ["ch20"],
    "userAnswer": null,
    "isCorrect": null,
    "isFavorite": false,
    "attemptCount": 0,
    "lastAttemptDate": null
  }
];

window.ch20Questions = ch20Questions;

if (typeof examData !== 'undefined') {
  examData.questions = examData.questions.filter(q => q.chapterId !== 'ch20');
  examData.questions.push(...ch20Questions);
}
